### ISSUE TITLE
Direct Upload Signed URL PUT failing with CORS error

### ISSUE THREAD

**Issue by nzee** [muxinc/mux-python#17]
I generated a signed_url by passing appropriate cors_origin as per my domain yet the generated URL, I am unable to PUT the video file from browser.

Here is the error I am getting:
`Access to fetch at 'https://storage.googleapis.com/video-storage-us-east1-....' from origin 'https://youreact.tv' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

And here is my backend code that generates the signed URL:

> uploads_api = mux_python.DirectUploadsApi(mux_python.ApiClient(configuration))
> 
> create_asset_request = mux_python.CreateAssetRequest(playback_policy=[mux_python.PlaybackPolicy.PUBLIC],passthrough="123")
> 
> create_upload_request = mux_python.CreateUploadRequest(timeout=3600, new_asset_settings=create_asset_request, cors_origin="https://youreact.tv")
> 
> create_upload_response = uploads_api.create_direct_upload(create_upload_request)

and here is the client side code that tries to PUT the video file:

> const upload = async (file) => {
> 
>             const upload = UpChunk.createUpload({
>                 endpoint: '{{ signed_url }}',                
>                 file: file            
>             });
> 
>             console.log("res:",upload) 
>         }

**Comment by GeneticGenesis** [comment]
Hi @nzee, thanks for raising this, we'll look into it on our side.

**Comment by GeneticGenesis** [comment]
Hey @nzee, I can't reproduce this on my end, we can happily use the URLs we're generating with mux-python with upchunk.

What we have seen historically that _may_ be causing this though is that your rendering engine may be escaping the URL that gets passed back from the SDK to your front end, and consequently into upchunk (we've seen this in mux-php a couple of times). To confirm this, try logging the URL directly from your app on the server side, and checking it against what ends up in your frontend.

If that doesn't solve it, please can you ping me (Phil) on help@mux.com and we're happy to debug this with you.

Thanks!
