### ISSUE TITLE
How to enable MP4 on already created asset

### ISSUE THREAD

**Issue by FelipeSBarros** [muxinc/mux-python#37]
Dear coolleagues. Thanks so much for the amazing work done.

I am trying to update an asset, just like presented [here](https://github.com/muxinc/mux-python/blob/master/examples/video/exercise-assets.py#L91), but passing the asset id to be updated from the list I got from `assets_api.list_assets()`, instead of an `assets_api.create_asset(create_asset_request)` object.

Error message I got is:
```
mux_python.exceptions.NotFoundException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'max-age=0, private, must-revalidate', 'Content-Length': '121', 'Content-Type': 'application/json; charset=utf-8', 'Date': 'Thu, 16 Sep 2021 12:57:44 GMT', 'Server': 'Mux API Server v1.131.2', 'X-Request-Id': 'FqVOyN_5MDLCiXUBWLmD'})
HTTP response body: {"error":{"type":"not_found","messages":["The requested resource either doesn't exist or you don't have access to it."]}}

```

The asset id exists and is the correct one. So, I am wondering if:  
* to do an update I need a special access?
* to update an asset the same must be an recently created asset and not an old one?

thanks in advance

**Comment by eropple** [comment]
Hey Felipe - sorry we didn't reply earlier to this one. We're investigating internally what's up here.

Thanks,
Ed

**Comment by FelipeSBarros** [comment]
Dear @eropple , thanks for the contact.

Just to give you more context about what a need to do:
Next week we will have an event using StreamYard. The streaming will be linked to mux.
After the event I will need to access all videos in high resolution for edition purpose.
This is way I have been trying tho iterate over all asset list enabling MP4 to, later, iterate again downloading them.

I wonder if [updating the asset to enable master access](https://github.com/muxinc/mux-python/blob/9edcbdacfea5604c2cc20e4322c7576855ce876d/examples/video/exercise-assets.py#L101) should be done instead of only enabling MP4 extension?

either ways I got the same error, as I am still using the asset id from `assets_api.list_assets()`.

Error message:
```
 raise NotFoundException(http_resp=r)
mux_python.exceptions.NotFoundException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'max-age=0, private, must-revalidate', 'Content-Length': '121', 'Content-Type': 'application/json; charset=utf-8', 'Date': 'Thu, 23 Sep 2021 11:37:48 GMT', 'Server': 'Mux API Server v1.131.9', 'X-Request-Id': 'FqdwfC7rpb6dlC0Aq9uG'})
HTTP response body: {"error":{"type":"not_found","messages":["The requested resource either doesn't exist or you don't have access to it."]}}

```

**Comment by eropple** [comment]
Hey Felipe - sorry for the delay, little bit swamped. You want the highest-quality MP4 we have, so you should want master access - but as you can see, our exercised examples don't seem to hit this same issue, so there might be something on your end of things that's causing trouble.

Are these test assets that you're using?

**Comment by FelipeSBarros** [comment]
@eropple , that is what we need: the highest-quality MP4.
By now, we have five or six test assets. By Monday 27th we will start receiving the stream content from the event.

I could understand that your exercise examples don't hit the same issue. I guess that perhaps there is something related to the fact that I am not using an `assets_api.create_asset(create_asset_request)` object, although seems to be reasonable trying to change the availability to the master asset from the asset list.
So, how could you help on this issue?
I already have confirmed with my coordinator that I have admin role. ( @delawen )
Perhaps I could share cod example showing how to update an asset from the asset list, enabling access to the master version?
Thanks in advance.

**Comment by philcluff** [comment]
Hey @FelipeSBarros, there's a full example of enabling Master Access in Python here:

https://github.com/muxinc/mux-python/blob/master/examples/video/exercise-assets.py#L101-L109

You'll need to pass the Asset ID from your List Assets call.

You'll then need to wait for the master to generate. We send you a `video.asset.master.ready` webhook when this is complete. You can then use the Get Asset call to get the master access URL.

You can see a full guide for enabling Master Access here: https://docs.mux.com/guides/video/download-for-offline-editing

If you continue to experience issues, please feel free to share the IDs of the Assets that you're trying to enable master access on with `help@mux.com`.

**Comment by FelipeSBarros** [comment]
Hi, @philcluff . This is what I was trying to do, and mentioned above.
Already sent to help email.
the process done is:

```
# Authentication Setup
configuration = mux_python.Configuration()
configuration.username = config('MUX_USERNAME')
configuration.password = config('MUX_PASSWORD')

# API Client Initialization
assets_api = mux_python.AssetsApi(mux_python.ApiClient(configuration))

list_assets_response = assets_api.list_assets()

#test with first video
asset = list_assets_response.data[0]

# master
update_asset_master_access_request = mux_python.UpdateAssetMasterAccessRequest(master_access="temporary")
asset_response_master = assets_api.update_asset_master_access(asset.id,
                                                              update_asset_master_access_request)

```

**Comment by philcluff** [comment]
Hi @FelipeSBarros, I've replied on the support request you raised but also putting it here for posterity. 

The API key you're using doesn't seem to have the `video:write` permission. If you re-create the API key with that permission, it should work just fine.

Thanks.

**Comment by FelipeSBarros** [comment]
Thanks a lot for your help @philcluff,  @eropple et al.
