### ISSUE TITLE
"max_continuous_duration" parameter

### ISSUE THREAD

**Issue by VirajDeshwal** [muxinc/mux-python#44]
Please add an example for "max_continuous_duration". There is no example available on how to use the "duration" parameter for a live stream. 
I am not able to find how to set the duration in API request.
I am getting the following error : "'Server': 'Mux API Server v1.158.3', 'X-Request-Id': 'FvnrJ5bJcVMDeN0Hi62B'})
HTTP response body: {"error":{"type":"invalid_parameters","messages":["Cannot use max continuous duration with test live streams"]}}"

**Comment by aminamos** [comment]
@VirajDeshwal have you added a card to your account and tried with a non-test stream? If you'd like to have a private conversation with support, submit a ticket here: https://www.mux.com/support

**Comment by VirajDeshwal** [comment]
> @VirajDeshwal have you added a card to your account and tried with a non-test stream? If you'd like to have a private conversation with support, submit a ticket here: https://www.mux.com/
No. I am trying to test the live stream with a demo account.

**Comment by VirajDeshwal** [comment]
Resolved after upgrading the account. Thank you

**Comment by trile127** [comment]
I get an error on this, on creating a test stream. I want to be able to make a test LiveStream. What's the work around? I had to downgrade the version back to 3.3.1

**Comment by philcluff** [comment]
Hey @trile127, apologies for the issue here, we're taking a deeper look now.

**Comment by VirajDeshwal** [comment]
@trile127 could you please post the response you are getting. And what field is unwanted ?

**Comment by trile127** [comment]
new_asset_settings = mux_python.CreateAssetRequest(playback_policy=[mux_python.PlaybackPolicy.PUBLIC])
        create_live_stream_request = mux_python.CreateLiveStreamRequest(
            playback_policy=[mux_python.PlaybackPolicy.PUBLIC],
            new_asset_settings=new_asset_settings,
            test=True,
        )

And my error is like this:
"'Server': 'Mux API Server v1.158.3', 'X-Request-Id': 'FvnrJ5bJcVMDeN0Hi62B'})
HTTP response body: {"error":{"type":"invalid_parameters","messages":["Cannot use max continuous duration with test live streams"]}}"

For mux-python 3.6.0

**Comment by VirajDeshwal** [comment]
@trile127 i had the same issue. Add the credit card in your account and this should fix your issue.

**Comment by philcluff** [comment]
Just to clarify here, this is an issue on Mux's end, and we're making a change to ensure that `test` mode stays available when using this SDK.

Thanks.

**Comment by jaredsmith** [comment]
The change to our system has been implemented -- as I understand it, if you have both `max_continuous_duration` and a test stream, the Mux API will now essentially override the `max_continuous_duration` and set it to 300 seconds.

Could you please try again and let me know if you're still having issues?

**Comment by trile127** [comment]
Fixed, thank you!

**Comment by VirajDeshwal** [comment]
@tri le you have to add the card and that should resolve your issue

Viraj Deshwal
6574459633
________________________________
