### ISSUE TITLE
Change "hls_segment_type" from .ts to .fmp4

### ISSUE THREAD

**Issue by VirajDeshwal** [muxinc/mux-python#46]
Hello, Currently my live stream is broadcasting the chunks in ".ts" format. I would like to change the "HLS_segement_type" to .fmp4. Is there a parameter I can tune to convert the .ts chunk into .fmp4?

**Comment by philcluff** [comment]
Hi @VirajDeshwal, we currently only deliver fmp4 fragments when your live stream is using the low latency mode. There is not an option to use fmp4 fragments for other streams or assets right now.

For product questions, please can you reach out to the team on https://mux.com/support going forward. 

Thanks!
