### ISSUE TITLE
Lower video resolution before download

### ISSUE THREAD

**Issue by rlleshi** [muxinc/mux-python#52]
Is there such an option? E.g. defining the width and height of the video before downloading it with `ux_python.AssetsApi(mux_python.ApiClient(config)).get_asset()`?

**Comment by philcluff** [comment]
Hi @rlleshi, we don't offer direct control over the resolutions of the video encoded, stored, or delivered.

When downloading MP4s, you can select from several different resolutions [as described here](https://docs.mux.com/guides/video/enable-static-mp4-renditions#create-the-mp4-streaming-url).

Thanks.
