### ISSUE TITLE
Additional cases where UnauthorizedException may raise?

### ISSUE THREAD

**Issue by bryantjamestech** [muxinc/mux-python#58]
Are there undocumented situations which might cause Mux to return a 401 (and therefore cause the client to raise an UnauthorizedException)?

I can't really share the code, but I can share the context:

- We are connecting to Mux via the Python client to create assets and create/delete tracks.
- We are currently using the same database locally and when deployed to production.
- We are currently using the same codebase locally and when deployed to production.
- We are currently using the same access tokens locally and when deployed to production.

Attempts to create or delete assets functions well enough in local. Attempts to create or delete assets raises an UnauthorizedException across our development, staging, and production environments.

The kicker, though, is that this all worked as recently as a week ago, and there were no new deploys to our production system before the issues started arising.

I'm wondering if there is potential that Mux would blacklist a server? All of our environments are deployed via managed Docker containers in DigitalOcean, so that seems the most noteworthy similarity between the three environments having issue.

**Comment by philcluff** [comment]
Hey @bryantjamestech, thanks for reaching out. 

This isn't expected, and we don't block specific servers, IP ranges etc.

`UnauthorizedException` would usually indicate that you're not valid credentials to Mux.

Could you do me a favour and [reach out to out support team](https://www.mux.com/support) with details including the API Key ID, and we can take a look in more details. 

Thanks!

**Comment by bryantjamestech** [comment]
Will do!
