### ISSUE TITLE
How to fix "Video is not currently available The live stream or video files are not ready yet." ?

### ISSUE THREAD

**Issue by smandava98** [muxinc/mux-python#76]
How do I just put a loading screen or autorefresh on the Mux Player when I get:

"Video is not currently available The live stream or video files are not ready yet." 

?

**Comment by JacquiManzi** [comment]
Hey @smandava98 , sorry for the late response on this. This doesn't appear to be an issue with the SDK, but if you reach out to us at https://mux.com/support we might be able to help out. Thanks!
