### ISSUE TITLE
Example of how to upload a video

### ISSUE THREAD

**Issue by xRagnorokx** [muxinc/mux-python#80]
Hi, 

I am struggling to use this library to upload videos to Mux. I have read through the documentation, ReadMe and examples in this repo. I have also been through the process of uploading to Mux using the web UI.

I can see the DirectUploadsApi and example makes what seems to be a "pre-request to upload", which returns a Google Storage URL to upload to and the info I need about where the upload will go/be called etc. But I seem to be missing the methods or documentation that then use or describe what I need to do with that URL to actually do the upload. 

Any help or guidance would be much appreciated! I think the TODO in https://github.com/muxinc/mux-python/blob/master/examples/video/exercise-uploads.py is probably what I need?

"# TODO: At some point I'd like to actually perform an upload here and check the state changes etc. but I don't have time right now."

Thanks

**Comment by xRagnorokx** [comment]
Ah, I found it on the Mux documentation: 

https://docs.mux.com/guides/upload-files-directly#2-use-that-url-to-upload-in-your-client

Specifically:

curl -v -X PUT -T myawesomevideo.mp4 "$URL_FROM_STEP_ONE"

**Comment by philcluff** [comment]
Hey @xRagnorokx, thanks for the feedback here - you're right that we don't currently expose helper functions in our server-side SDKs for sending a file via direct uploads - we do offer SDKs for [Web](https://github.com/muxinc/upchunk), [iOS](https://docs.mux.com/guides/upload-video-directly-from-ios-or-ipados), and [Android](https://docs.mux.com/guides/upload-video-directly-from-android) for this though. I'll make sure to pass this feedback to the SDKs team. 

Thanks!
